== Irma Examples

=== Five Configurations that will Compute

Confirm that the Weather_Routing Plugin has been installed.

__*Files & Pathnames* __

It is important that you use this configuration for Windows (Linux use
comparable User accessible directories):

. Main Path for support files:
_C:\ProgramData\opencpn\plugins\weather_routing_
. WeatherRoutingConfiguration.xml:
_C:\ProgramData\opencpn\plugins\weather_routing_
. Polar Files (.pol,.txt,.csv):
_C:\ProgramData\opencpn\plugins\weather_routing\polars_
. Boat.Xml Files: _C:\ProgramData\opencpn\plugins\weather_routing\boat_
. Grib-Sample File:
_C:\ProgramData\opencpn\plugins\weather_routing\grib-sample_

(Note the weather_routing installation may not create these files in the
correct location, and may put them under _C:\Program Files
(x86)\opencpn\plugins\weather_routing/data_. If this is the case, just
download the Weather Routing Setup files below and install as shown
above.

==== Weather Routing Setup Files

Download and Unzip files and directories to
_C:\ProgramData\opencpn\plugins\weather_routing_

image:/opencpn/manual/plugins/weather_routing/weather-routing-setup.zip[Weather
Routing Setup]

Unzip and install files & directories into
_C:\ProgramData\opencpn\plugins\weather_routing_ to follow the locations
above. These files will provide you with sample files to help learn how
to weather_route.

==== Run some Weather Routing Routes

. Start Climatology_pi, although it will start automatically if called.
. Start Grib_pi and open the Irma-Jose-2017090618.gfs.grib2 file located
in _C:\ProgramData\opencpn\plugins\weather_routing\grib-sample_ or just
copy it to your normal grib file location.
. Set the Grib Date to Wed, Sept 6 2017, UTC 21:00 and get the screen
centered on the grib.
. Then open Weather_routing_pi, you may be pointing at the wrong
directory, so Pick "_File > Open_" and browse to
_C:\ProgramData\opencpn\plugins\weather_routing_ and then select and
open "_WeatherRoutingConfiguration.xml_".
. Confirm the "Boat section" path is correct as shown above in the
Pathname list.
. Confirm the "Polar" path is correct as shown above in the Pathname
list.
. In the menu you should find 5 configurations for routes in the
Caribbean.
. Pick a route and then select "Compute from the bottom of the menu.
. Check that the isobars and route is drawn. Then step through the
Grib_pi changing the time to see where the boat is located and how the
wind changes.
. Try "Computing" the other routes, noticing how the settings have been
changed, and what files are being used.
. Once you are pretty confident about this, go to the next step, which
is to create your own configurations.

==== Computation of 5 Routes

These are 5 Weather Routings in "*Weather-Routing-Setup*" that should
*Complete* when using the small grib file for hurricane Irma.
Weather_routing would not normally be used for this, however

pandoc 2.14.0.2

https://pandoc.org
