/* Autogenerated by png2wx.pl on Tue Mar  5 02:26:11 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>

extern void initialize_images(void);

extern wxBitmap *_img_WeatherRouting;

#ifdef PLUGIN_USE_SVG
   extern wxString _svg_weather_routing;
   extern wxString _svg_weather_routing_rollover;
   extern wxString _svg_weather_routing_toggled;
#endif

#endif /* ICONS_H */
