/* Autogenerated by png2wx.pl on Tue Mar  5 02:26:11 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_WeatherRouting;

#endif /* ICONS_H */
