/* Autogenerated by png2wx.pl on Wed Jun  6 15:19:19 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_advancedrouting;

#endif /* ICONS_H */
